name: Test and Build Docker Images

on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push remat-clowder-extractor-base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/re-mat/remat-clowder-extractor-base:${{ env.branch }}
            ghcr.io/re-mat/remat-clowder-extractor-base:latest

      - name: Build and push experiment-from-excel image
        uses: docker/build-push-action@v4
        with:
          context: ./src/clowder_extractors/experiment_from_excel
          file : ./src/clowder_extractors/experiment_from_excel/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/re-mat/experiment-from-excel:${{ env.branch }}
          build-args: |
            IMAGE_TAG=${{ env.branch }}

      - name: Build and push parameters from txt image
        uses: docker/build-push-action@v4
        with:
          context: ./src/clowder_extractors/parameter_extractor
          file: ./src/clowder_extractors/parameter_extractor/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/re-mat/parameter-extractor:${{ env.branch }}
          build-args: |
            IMAGE_TAG=${{ env.branch }}

      - name: Build and push csv stripper image
        uses: docker/build-push-action@v4
        with:
          context: ./src/clowder_extractors/csv_stripper
          file: ./src/clowder_extractors/csv_stripper/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/re-mat/dsc-csv-stripper:${{ env.branch }}
          build-args: |
            IMAGE_TAG=${{ env.branch }}
